Repository ISIS3510-202410-Team33/mobile_flutter, pull requests merged in 2024-05, with the labels that each got.

#89 Final fixes pre - sprint 4
  ventura_front/lib/screens/home/components/options_component.dart
  ventura_front/lib/screens/home/components/signout_button.dart
  ventura_front/lib/screens/home/view.dart
  ventura_front/lib/screens/loading/view.dart
  ventura_front/lib/screens/login/view.dart
  ventura_front/lib/screens/map/components/rateIcon_component.dart
  ventura_front/lib/screens/map/view.dart
  ventura_front/lib/screens/profile/view.dart
  ventura_front/lib/screens/signUp/view.dart
  ventura_front/lib/services/models/location_model.dart
  ventura_front/lib/services/view_models/locations_viewmodel.dart
  ventura_front/lib/services/view_models/user_viewModel.dart
Labels: bug, critical, Sprint 3

#91 Fixes Notifications, Proximity, Cache image
  ventura_front/lib/icons/campus_ng.jpg
  ventura_front/lib/main.dart
  ventura_front/lib/screens/home/components/ButtonElement.dart
  ventura_front/lib/screens/home/components/cachedImage_component.dart
  ventura_front/lib/screens/home/components/imageSlider_component.dart
  ventura_front/lib/screens/home/components/university_component.dart
  ventura_front/lib/screens/loading/view.dart
  ventura_front/lib/screens/login/view.dart
  ventura_front/lib/screens/map/view.dart
  ventura_front/lib/screens/notifications/view.dart
  ventura_front/lib/screens/signUp/view.dart
  ventura_front/lib/sensors_components/proximity_sensor.dart
  ventura_front/lib/services/repositories/user_repository.dart
  ventura_front/lib/services/view_models/calification_viewmodel.dart
  ventura_front/lib/services/view_models/notification_viewmodel.dart
  ventura_front/macos/Flutter/GeneratedPluginRegistrant.swift
  ventura_front/pubspec.lock
  ventura_front/pubspec.yaml
Labels: bug, enhancement, critical, Sprint 3

#92 Feature/sprint3-bq4-#74
  ventura_front/lib/main.dart
  ventura_front/lib/screens/home/components/signout_button.dart
  ventura_front/lib/screens/home/components/weather_component.dart
  ventura_front/lib/screens/home/view.dart
  ventura_front/lib/screens/login/view.dart
  ventura_front/lib/screens/map/view.dart
  ventura_front/lib/screens/notifications/view.dart
  ventura_front/lib/screens/profile/view.dart
  ventura_front/lib/sensors_components/proximity_sensor.dart
  ventura_front/lib/services/repositories/profile_repository.dart
  ventura_front/lib/services/view_models/connection_viewmodel.dart
  ventura_front/lib/services/view_models/locations_viewmodel.dart
  ventura_front/lib/services/view_models/profile_viewmodel.dart
  ventura_front/linux/flutter/generated_plugin_registrant.cc
  ventura_front/linux/flutter/generated_plugins.cmake
  ventura_front/macos/Flutter/GeneratedPluginRegistrant.swift
  ventura_front/pubspec.lock
  ventura_front/pubspec.yaml
  ventura_front/windows/flutter/generated_plugin_registrant.cc
  ventura_front/windows/flutter/generated_plugins.cmake
Labels: bug, enhancement, critical, Sprint 3

#100 Screen Grades implemented - issue #98
  ventura_front/.vscode/launch.json
  ventura_front/devtools_options.yaml
  ventura_front/lib/main.dart
  ventura_front/lib/screens/grades/view.dart
  ventura_front/lib/screens/home/components/ButtonElement.dart
  ventura_front/lib/screens/home/components/options_component.dart
  ventura_front/lib/screens/home/view.dart
  ventura_front/lib/screens/login/view.dart
  ventura_front/lib/screens/settings/view.dart
  ventura_front/lib/services/models/course_model.dart
  ventura_front/lib/services/models/grade_model.dart
  ventura_front/lib/services/repositories/grades_repository.dart
  ventura_front/lib/services/view_models/calification_viewmodel.dart
  ventura_front/lib/services/view_models/grades_viewmodel.dart
  ventura_front/pubspec.lock
  ventura_front/pubspec.yaml
Labels: enhancement, feature, critical, Sprint 4

#102 Screen Grades implemented - issue #95
  ventura_front/lib/screens/home/components/ButtonElement.dart
  ventura_front/lib/screens/home/components/options_component.dart
  ventura_front/lib/screens/schedule/view.dart
Labels: feature, critical, Sprint 4

#103 Feature/logic courses implementation #94
  ventura_front/lib/screens/courses/view.dart
  ventura_front/lib/screens/notifications/view.dart
  ventura_front/lib/services/models/course_model.dart
  ventura_front/lib/services/repositories/courses_repository.dart
  ventura_front/lib/services/view_models/course_viewmodel.dart
Labels: enhancement, feature, Sprint 4

#104 Logic implementation
  ventura_front/lib/screens/grades/view.dart
  ventura_front/lib/screens/notifications/view.dart
  ventura_front/lib/services/models/course_model.dart
  ventura_front/lib/services/models/grade_model.dart
  ventura_front/lib/services/repositories/grades_repository.dart
  ventura_front/lib/services/view_models/grades_viewmodel.dart
  ventura_front/pubspec.lock
  ventura_front/pubspec.yaml
Labels: enhancement, feature, critical, Sprint 4

#105 Logic Agenda implemented - issue #96
  ventura_front/lib/services/models/schedule_model.dart
  ventura_front/lib/services/repositories/schedule_repository.dart
  ventura_front/lib/services/view_models/schedule_viewmodel.dart
Labels: feature, critical, Sprint 4

#106 Feature/optimizations-#97
  ventura_front/.vscode/settings.json
  ventura_front/android/settings.gradle
  ventura_front/lib/screens/login/view.dart
Labels: enhancement, critical, Sprint 4

#108 Course Logic bugs fixed
  ventura_front/android/app/build.gradle
  ventura_front/lib/screens/grades/view.dart
  ventura_front/lib/screens/home/components/signout_button.dart
  ventura_front/lib/services/models/course_model.dart
  ventura_front/lib/services/models/grade_model.dart
  ventura_front/lib/services/repositories/courses_repository.dart
  ventura_front/lib/services/repositories/grades_repository.dart
  ventura_front/lib/services/repositories/sqflite_db.dart
  ventura_front/lib/services/view_models/course_viewmodel.dart
  ventura_front/lib/services/view_models/grades_viewmodel.dart
Labels: bug, critical

#110 Implementation of changes
  ventura_front/lib/screens/home/components/options_component.dart
  ventura_front/lib/screens/home/view.dart
Labels: critical

#111 Bug with SnackBar fixed
  ventura_front/lib/screens/home/view.dart
Labels: bug, critical

#114 Schedule calendar bug Fixed!
  ventura_front/lib/screens/home/components/ButtonElement.dart
  ventura_front/lib/screens/schedule/task_calendar.dart
  ventura_front/lib/screens/schedule/view.dart
  ventura_front/lib/services/models/schedule_model.dart
  ventura_front/lib/services/repositories/schedule_repository.dart
  ventura_front/lib/services/view_models/schedule_viewmodel.dart
  ventura_front/pubspec.yaml
Labels: bug, enhancement, critical

#115 Implementation of BQ
  ventura_front/lib/screens/grades/view.dart
  ventura_front/lib/services/models/grade_model.dart
  ventura_front/lib/services/repositories/grades_repository.dart
  ventura_front/lib/services/repositories/sqflite_db.dart
  ventura_front/lib/services/view_models/grades_viewmodel.dart
  ventura_front/pubspec.lock
Labels: bug, critical

#117 Fixes in feature courses and bq
  ventura_front/lib/screens/courses/components/addCourses_component.dart
  ventura_front/lib/screens/courses/components/coursesDetails_component.dart
  ventura_front/lib/screens/courses/view.dart
  ventura_front/lib/screens/home/components/ButtonElement.dart
  ventura_front/lib/screens/home/components/options_component.dart
  ventura_front/macos/Flutter/GeneratedPluginRegistrant.swift
  ventura_front/pubspec.lock
  ventura_front/pubspec.yaml
  ventura_front/windows/flutter/generated_plugin_registrant.cc
  ventura_front/windows/flutter/generated_plugins.cmake
Labels: bug, critical, Sprint 4
