Repository ISIS3510-202410-Team33/mobile_flutter, pull requests merged in 2024-04, with the labels that each got.

#38 MVVM and alerts implemented for weather #37
  ventura_front/lib/icons/clear.png
  ventura_front/lib/icons/cloud.png
  ventura_front/lib/icons/rain.png
  ventura_front/lib/screens/home/components/weather_component.dart
  ventura_front/lib/screens/home/view.dart
  ventura_front/lib/services/repositories/weather_repository.dart
  ventura_front/lib/services/view_models/weather_viewmodel.dart
Labels: enhancement, Sprint 2

#39 Connection of map screen and location components with API Rest, and updating functionalities like ubicate
  ventura_front/android/app/src/main/AndroidManifest.xml
  ventura_front/lib/screens/map/view.dart
  ventura_front/lib/screens/signUp/view.dart
  ventura_front/lib/services/models/location_model.dart
  ventura_front/lib/services/models/user_location_model.dart
  ventura_front/lib/services/repositories/locations_repository.dart
  ventura_front/lib/services/view_models/locations_viewmodel.dart
  ventura_front/lib/services/view_models/user_viewModel.dart
Labels: bug, enhancement, critical, Sprint 3

#43 Finalization of logic implementation for sign out feature
  ventura_front/lib/icons/log-out-icon.png
  ventura_front/lib/screens/components/header_component.dart
  ventura_front/lib/screens/home/components/signout_button.dart
  ventura_front/lib/screens/home/view.dart
  ventura_front/lib/screens/login/view.dart
  ventura_front/lib/screens/map/view.dart
  ventura_front/lib/screens/profile/view.dart
  ventura_front/lib/services/repositories/user_repository.dart
  ventura_front/lib/services/view_models/user_viewModel.dart
Labels: enhancement, critical, Sprint 3

#45 Implementation of UI changes for screens: Loading, SignIn, SignUp
  ventura_front/lib/icons/goose-complete.png
  ventura_front/lib/screens/loading/view.dart
  ventura_front/lib/screens/login/view.dart
  ventura_front/lib/screens/signUp/view.dart
  ventura_front/lib/services/repositories/user_repository.dart
Labels: bug, enhancement, critical, Sprint 3

#49 Implementation of .env file
  ventura_front/.env
  ventura_front/.properties
  ventura_front/lib/main.dart
  ventura_front/lib/services/repositories/locations_repository.dart
  ventura_front/pubspec.lock
  ventura_front/pubspec.yaml
Labels: enhancement, Sprint 3

#51 BQ1 - Implementation
  ventura_front/.env
  ventura_front/lib/screens/map/view.dart
  ventura_front/lib/services/models/location_model.dart
  ventura_front/lib/services/repositories/locations_repository.dart
  ventura_front/lib/services/view_models/locations_viewmodel.dart
Labels: feature, critical, Sprint 3

#57 BQ3 - Implementation
  ventura_front/lib/screens/components/header_component.dart
  ventura_front/lib/screens/home/components/signout_button.dart
  ventura_front/lib/screens/home/components/weather_component.dart
  ventura_front/lib/screens/map/view.dart
  ventura_front/lib/screens/profile/components/progress_bar.dart
  ventura_front/lib/screens/profile/view.dart
  ventura_front/lib/services/repositories/profile_repository.dart
  ventura_front/lib/services/view_models/profile_viewmodel.dart
  ventura_front/macos/Flutter/GeneratedPluginRegistrant.swift
  ventura_front/pubspec.lock
  ventura_front/pubspec.yaml
Labels: enhancement, feature, critical, Sprint 3

#61 Implementation of user connection with backend
  ventura_front/android/app/src/main/AndroidManifest.xml
  ventura_front/lib/screens/home/components/signout_button.dart
  ventura_front/lib/screens/home/view.dart
  ventura_front/lib/screens/loading/view.dart
  ventura_front/lib/screens/login/view.dart
  ventura_front/lib/screens/map/view.dart
  ventura_front/lib/screens/profile/view.dart
  ventura_front/lib/screens/signUp/view.dart
  ventura_front/lib/services/models/user_location_model.dart
  ventura_front/lib/services/models/user_model.dart
  ventura_front/lib/services/models/weather_model.dart
  ventura_front/lib/services/repositories/user_repository.dart
  ventura_front/lib/services/view_models/connection_viewmodel.dart
  ventura_front/lib/services/view_models/locations_viewmodel.dart
  ventura_front/lib/services/view_models/user_viewModel.dart
Labels: enhancement, feature, critical, Sprint 3

#70 Weather offline scenario
  ventura_front/lib/icons/error.png
  ventura_front/lib/screens/home/components/weather_component.dart
  ventura_front/lib/screens/home/view.dart
  ventura_front/lib/services/models/weather_model.dart
  ventura_front/lib/services/repositories/profile_repository.dart
  ventura_front/lib/services/view_models/connection_viewmodel.dart
Labels: enhancement, feature, Sprint 3

#62 Implementation Button Page University
  ventura_front/lib/screens/home/components/university_component.dart
  ventura_front/pubspec.lock
  ventura_front/pubspec.yaml
Labels: bug, enhancement, Sprint 3

#73 Implementation of cache in locations
  ventura_front/lib/data/initial-locations.json
  ventura_front/lib/screens/components/header_component.dart
  ventura_front/lib/screens/home/components/notifications_button.dart
  ventura_front/lib/screens/home/view.dart
  ventura_front/lib/screens/loading/components/no_connection_screen.dart
  ventura_front/lib/screens/loading/view.dart
  ventura_front/lib/screens/map/view.dart
  ventura_front/lib/services/repositories/locations_repository.dart
  ventura_front/lib/services/view_models/connection_viewmodel.dart
  ventura_front/lib/services/view_models/locations_viewmodel.dart
  ventura_front/pubspec.yaml
Labels: enhancement, feature, critical, Sprint 3

#75 Implementation of cache for weather
  ventura_front/lib/main.dart
  ventura_front/lib/services/models/weather_model.dart
  ventura_front/lib/services/view_models/weather_viewmodel.dart
Labels: enhancement, feature, critical, Sprint 3

#77 BQ4 - Implementation
  ventura_front/lib/screens/map/components/rateIcon_component.dart
  ventura_front/lib/screens/map/view.dart
  ventura_front/lib/services/repositories/locations_repository.dart
  ventura_front/lib/services/view_models/locations_viewmodel.dart
Labels: feature, critical, Sprint 3

#76 Notifications
  ventura_front/lib/screens/notifications/view.dart
  ventura_front/lib/services/repositories/locations_repository.dart
  ventura_front/lib/services/view_models/notification_viewmodel.dart
Labels: enhancement, feature, critical, Sprint 3

#83 Iconapp
  ventura_front/android/app/src/main/AndroidManifest.xml
  ventura_front/android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  ventura_front/android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  ventura_front/android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  ventura_front/android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  ventura_front/android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  ventura_front/pubspec.lock
  ventura_front/pubspec.yaml
Labels: bug, Sprint 3

#87 Fixing errors in location screen - issue #78
  ventura_front/android/app/src/main/AndroidManifest.xml
  ventura_front/lib/mvvm_components/observer.dart
  ventura_front/lib/mvvm_components/viewmodel.dart
  ventura_front/lib/screens/components/header_component.dart
  ventura_front/lib/screens/home/components/ButtonElement.dart
  ventura_front/lib/screens/home/components/notifications_button.dart
  ventura_front/lib/screens/home/components/options_component.dart
  ventura_front/lib/screens/home/components/signout_button.dart
  ventura_front/lib/screens/home/components/university_component.dart
  ventura_front/lib/screens/home/view.dart
  ventura_front/lib/screens/loading/components/no_connection_screen.dart
  ventura_front/lib/screens/loading/view.dart
  ventura_front/lib/screens/login/view.dart
  ventura_front/lib/screens/map/view.dart
  ventura_front/lib/screens/notifications/view.dart
  ventura_front/lib/screens/profile/view.dart
  ventura_front/lib/screens/settings/view.dart
  ventura_front/lib/screens/signUp/view.dart
  ventura_front/lib/services/models/user_location_model.dart
  ventura_front/lib/services/repositories/gps_repository.dart
  ventura_front/lib/services/repositories/locations_repository.dart
  ventura_front/lib/services/view_models/connection_viewmodel.dart
  ventura_front/lib/services/view_models/locations_viewmodel.dart
  ventura_front/lib/services/view_models/notification_viewmodel.dart
  ventura_front/lib/services/view_models/user_viewModel.dart
Labels: bug, Sprint 3
